--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.2 (Debian 16.2-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Contacts" (
    "Id" integer NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "CategoryId" integer NOT NULL,
    "SubcategoryId" integer,
    "Phone" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL
);


ALTER TABLE public."Contacts" OWNER TO postgres;

--
-- Name: Contacts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Contacts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Contacts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Subcategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Subcategories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "CategoryId" integer NOT NULL
);


ALTER TABLE public."Subcategories" OWNER TO postgres;

--
-- Name: Subcategories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Subcategories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Subcategories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    "Id" integer NOT NULL,
    "FirstName" text,
    "LastName" text,
    "Username" text,
    "Password" text,
    "Token" text,
    "Role" text,
    "Email" text,
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp with time zone NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("Id", "Name") FROM stdin;
1	Służbowy
2	Prywatny
3	Inny
\.


--
-- Data for Name: Contacts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Contacts" ("Id", "FirstName", "LastName", "Email", "Password", "CategoryId", "SubcategoryId", "Phone", "DateOfBirth") FROM stdin;
1	Florian	Gaffke	aaaa@gmail.com	123	2	\N	111111111	-infinity
\.


--
-- Data for Name: Subcategories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Subcategories" ("Id", "Name", "CategoryId") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240327184610_InitialCreate	6.0.10
20240327204434_AddCategory	6.0.10
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users ("Id", "FirstName", "LastName", "Username", "Password", "Token", "Role", "Email", "RefreshToken", "RefreshTokenExpiryTime") FROM stdin;
2	Jan	Kowalski	Jan	YVbi43+eqp9yprxOjWn/p2NGTdHVs0E/ETvTGCIaK+bOXa4J	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVXNlciIsIm5hbWUiOiJKYW4iLCJuYmYiOjE3MTE1NjYwMTIsImV4cCI6MTcxMTU2NjAyMiwiaWF0IjoxNzExNTY2MDEyfQ.SQN8Gsi4vA5BTu0lfLXuzD8JC6GqIluBqkB0ugrF_0g	User	l@wp.pl	PNIWQ3u1k2WwehyfXBH+hS/hvOrSAgEMM4QjNFTb8hVxh3VxWPeKkL2Un9JR/bi6AbEPALLCxkiPVp/MiWGdTg==	2024-04-01 18:00:12.524413+00
1	Florian	Gaffke	Florian	CQ2pajEML3YIc5htHWfV7rcVh5ZcP9P8ltHY5kAvCzRei2EM	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVXNlciIsIm5hbWUiOiJGbG9yaWFuIiwibmJmIjoxNzExNTczNDMwLCJleHAiOjE3MTE1NzM0NDAsImlhdCI6MTcxMTU3MzQzMH0.YHfgQg_xsxjReQDwcqrQzuIU7uZfROaTyA9X0YVRUAw	User	a@gmail.com	ngXXwt+cvRLcCNeCiFe6sPiFyXp+bbz8kAlsus+S6ngyRgMch5ruMZ/2tFkX3WBV7RkbH+usld2/XDcfF79KhQ==	2024-04-01 20:03:50.974185+00
\.


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 1, false);


--
-- Name: Contacts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Contacts_Id_seq"', 1, true);


--
-- Name: Subcategories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Subcategories_Id_seq"', 1, false);


--
-- Name: users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."users_Id_seq"', 2, true);


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: Contacts PK_Contacts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contacts"
    ADD CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id");


--
-- Name: Subcategories PK_Subcategories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Subcategories"
    ADD CONSTRAINT "PK_Subcategories" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY ("Id");


--
-- Name: IX_Contacts_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Contacts_CategoryId" ON public."Contacts" USING btree ("CategoryId");


--
-- Name: IX_Contacts_SubcategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Contacts_SubcategoryId" ON public."Contacts" USING btree ("SubcategoryId");


--
-- Name: IX_Subcategories_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Subcategories_CategoryId" ON public."Subcategories" USING btree ("CategoryId");


--
-- Name: Contacts FK_Contacts_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contacts"
    ADD CONSTRAINT "FK_Contacts_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- Name: Contacts FK_Contacts_Subcategories_SubcategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contacts"
    ADD CONSTRAINT "FK_Contacts_Subcategories_SubcategoryId" FOREIGN KEY ("SubcategoryId") REFERENCES public."Subcategories"("Id");


--
-- Name: Subcategories FK_Subcategories_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Subcategories"
    ADD CONSTRAINT "FK_Subcategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

